language: go

go:
  - "1.18"
  - "1.19"

stages:
  - test

jobs:
  include:
    - stage: test
      go: "1.18"
      script:
        - echo "Running tests in the 'test' stage for Go 1.18"
    - stage: test
      go: "1.19"
      script:
        - echo "Running tests in the 'test' stage for Go 1.19"
