language: python
python:
  - "3.8"
  - "3.9"

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      python: "3.8"
      script:
        - echo "Running tests in the 'test' stage for Python 3.8"
    - stage: test
      python: "3.9"
      script:
        - echo "Running tests in the 'test' stage for Python 3.9"
    - stage: deploy
      python: "3.8"
      script:
        - echo "Deployment stage for Python 3.8"
    - stage: deploy
      python: "3.9"
      script:
        - echo "Deployment stage for Python 3.9"
