language: go

go:
  - "1.18"
  - "1.19"

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - echo "This is the build stage."
        - go version
        - echo "Build stage completed successfully."
    
    - stage: test
      script:
        - echo "This is the test stage."
        - go test ./...
        - echo "Test stage completed successfully."
