language: python
python:
  - "3.8"
  - "3.9"

env:
  - secure: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2V2ZXJ5X3ZhbCI6ImlzdGQxfHAzZC5vcmZyYWRnb2IkZXFzLm=="  # Your encrypted SECRET_KEY

script:
  - echo "Decrypted variable value is $SECRET_KEY"

before_deploy:
  - echo "This is just a test for encrypted variables in a forked repo"
