language: python
python:
  - "3.8"
  - "3.9"

env:
  - secure: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2V2ZXJ5X3ZhbCI6ImlzdGQxfHAzZC5vcmZyYWRnb2IkZXFzLm=="  # Your encrypted SECRET_KEY

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      python: "3.8"
      script:
        - echo "Running tests in the 'test' stage"
        - echo "Decrypted variable value is $SECRET_KEY"
    - stage: test
      python: "3.9"
      script:
        - echo "Running tests in the 'test' stage"
        - echo "Decrypted variable value is $SECRET_KEY"
    - stage: deploy
      python: "3.8"
      script:
        - echo "Deployment stage for Python 3.8"
        - echo "Deploying application..."
    - stage: deploy
      python: "3.9"
      script:
        - echo "Deployment stage for Python 3.9"
        - echo "Deploying application..."

before_deploy:
  - echo "This is just a test for multi-stage builds"
